#if !canImport(ObjectiveC)
import XCTest

extension CliTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CliTests = [
        ("testCli", testCli),
        ("testCommand", testCommand),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CliTests.__allTests__CliTests),
    ]
}
#endif
